### ISSUE TITLE
where is the pretrained model named "model_ckpt.pt"？

### ISSUE THREAD

**Issue by tyrink** [OrLichter/lcm-lookahead#1]
The checkpoint_path named "model_ckpt.pt" is not found.

**Comment by rinongal** [comment]
Are you trying to run inference? 
The readme section on inference has [a link](https://huggingface.co/rinong/lcm_lookahead) to our pre-trained models. 
Just download one of them and point at them (remember to set --no-kv if you're using the no_kv checkpoint).

**Comment by tyrink** [comment]
Yes, I want to run inference. Did you mean that I can directly replace 'cfg.checkpoint_path' with the path to the 'encoder_plus_adapter_ckpt.bin' file and load the given .bin file with msg = adapter.load_state_dict(torch.load(cfg.checkpoint_path), strict=True)?

**Comment by rinongal** [comment]
Yep. 

Just use `--checkpoint_path <path_to_ckpt_dir>/encoder_plus_adapter_ckpt.bin` when calling the inference script.
It's a .bin file and not a .pt because it was saved by HF's accelerate, but it gets loaded just fine.

**Comment by tyrink** [comment]
However, there seems to be something wrong. 
![image](https://github.com/OrLichter/lcm-lookahead/assets/75239935/c3b348ff-fbd5-453e-a35c-1fdd449a8a87)

**Comment by rinongal** [comment]
I just set up a new environment + downloaded the checkpoint from HF and I can't seem to replicate this issue.
Can you verify that you have the same diffusers, transformers and pytorch versions from the `environment.yaml`?

Can you also post the full command you are running?

**Comment by tyrink** [comment]
I have updated the diffusers version and everything works fine now, thanks!

**Comment by rinongal** [comment]
Great. Closing this since it seems everything is working. Feel free to reopen if you need more help.
